apiVersion: v1
kind: Template
metadata:
  name: hac-dev
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: hac-dev
    spec:
      API:
        versions:
          - v1
      assetsPrefix: api/plugins
      deploymentRepo: 'http://github.com/openshift/hac-dev'
      envName: ${ENV_NAME}
      frontend:
        paths:
          - /api/plugins/hac-dev
      image: ${IMAGE}:${IMAGE_TAG}
      title: hac-dev
    akamaiCacheBustPaths:
        - /api/plugins/hac-dev/app.info.deps.json
        - /api/plugins/hac-dev/app.info.json
        - /api/plugins/hac-dev/plugin-entry.js
        - /api/plugins/hac-dev/plugin-manifest.json
parameters:
  - name: IMAGE_TAG
    value: latest
  - name: IMAGE
    value: quay.io/cloudservices/hac-dev-frontend
  - name: ENV_NAME
    value: ephem-hac
