apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
spec:
  componentName:
  application: test-application
  source:
    git:
      url:
  containerImage:
